In [21]:
import numpy as np

In [22]:
test_array = np.array([1, 4, 5, 8], float)
print(test_array)
print(type(test_array))
type(test_array[3])

[1. 4. 5. 8.]
<class 'numpy.ndarray'>


numpy.float64

In [23]:
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [24]:
np.ones(shape=(10,),dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [25]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.empty(shape=(10,),dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [27]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.eye(N=3,M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [30]:
np.random.uniform(0,1,10).reshape(2,5)

array([[0.25331233, 0.41222278, 0.5106025 , 0.72259643, 0.8590351 ],
       [0.10666936, 0.32939068, 0.88848364, 0.07301316, 0.61354696]])

In [31]:
np.random.normal(0,1,10).reshape(2,5)

array([[-1.5737827 , -0.42138447,  0.71386621, -0.64458677,  0.72212718],
       [-0.33431425, -0.61823409,  0.81161524, -0.02068087,  0.49284416]])

In [32]:
test_array=np.arange(1,11)

In [33]:
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
test_array.sum(dtype=np.float)

C:\Users\hyunj\AppData\Local\Temp/ipykernel_24692/3740136754.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test_array.sum(dtype=np.float)


55.0

In [37]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a<4

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [39]:
np.any(a>5)

True

In [40]:
np.all(a>4)

False

In [41]:
np.any(a>5)

True